### PR TITLE
Issue #3067 remove double quotes option type switch

### PR DESCRIPTION
**Pull request by ViorelEremia**
@andreiglingeanu , @danyj , @ange007 - please test

### CODE REVIEW

**Comment by danyj** [comment]
you guys need to be careful with this one , 
I stooped using the option long time ago and have maybe 2 instances 
but many devs relied on it since Unyson release. The change must be announced prominently.

**Comment by danyj** [comment]
crap , i take that back , have many instances and have used @moldcraft  example 
like 

```
			'show_map' => array(
				'label' => __('Show map?', 'creatus'),
				'desc'  => esc_html__('Show/hide event map location', 'creatus'),
				'type'  => 'switch',
				'right-choice' => array(
					'value' => 'show',
					'label' => __('Show', 'creatus')
				),
				'left-choice' => array(
					'value' => 'hide',
					'label' => __('Hide', 'creatus')
				),
				'value' => 'show',
			),
```

string values , everywhere


@ViorelEremia   is the option now returning boolean only ?

**Comment by danyj** [comment]
see this 
https://github.com/ThemeFuse/Unyson/issues/670#issuecomment-111580998
https://github.com/ThemeFuse/Unyson/issues/1449#issuecomment-209128145

**Comment by andreiglingeanu** [comment]
We guys have to be very careful with that, it really can cause a lot of troubles.

**Comment by danyj** [comment]
I rather propose switch2  than mess everyone up now

**Comment by ange007** [comment]
Can add special parameter "to_json" (or other name) instead of switch2?

**Comment by ange007** [comment]
Or the behavior is changing a lot _(I have not studied it yet)_?

**Comment by danyj** [comment]
> Can add special parameter "to_json" 

switch would still be "buggy"  ,  if you want it done right than v2 is the safest bet and devs can slowly adapt to it

**Comment by andreiglingeanu** [comment]
> if you want it done right than v2 is the safest bet and devs can slowly adapt to it

yes, that's the only viable option

**Comment by danyj** [comment]
and we should not forget that multi-picker depends on this option also , so lets play this one safe for everyone

**Comment by andreiglingeanu** [comment]
@danyj Indeed, good mention, `multi-picker` is very tightly coupled with `switch`:

https://github.com/ThemeFuse/Unyson/blob/f60dc51b4d5d767bd8bac22d1c2721361affa167/framework/includes/option-types/multi-picker/static/js/multi-picker.js#L157-L164

**Pull request closed without merging**
