### PR TITLE
fix($option-types): makes the db value of checkboxes more robust

### PR DESCRIPTION
**Pull request by andreiglingeanu**
First of all, this change will make sure that each key from choices will be present in the final
value. This is very important and helps a lot by avoiding useless checks in templates that consume
the values.

One example would be that you'll need to do something like that in your `view.php`'s

```php
if (isset($atts['checkboxes_value']['first']) && $atts['checkboxes_value']['first']) {
  // Do action
}
```

With that change, you could skip the `isset(...)` call.

### CODE REVIEW

**Comment by andreiglingeanu** [comment]
Hm, diff looks very strange. The format is actually 🆗.

**Comment by danyj** [comment]
great , finally someone saw this

**Comment by danyj** [comment]
@andreiglingeanu ,  we should not have done this , since 2 years we all relied on unchecked ones not being present in array and have used that array to be filled with only items that we need, now everything is in , I used this in sql to get specific post type , now all post types are always in . one thing is out now I have to weed things out of the array

**Comment by danyj** [comment]
@ViorelEremia   this change  rasied huge issue ,  @andreiglingeanu  is reverting it back , when do you think you can get 2.8.0 out ?

**Pull request merged**
