### PR TITLE
Few changes

### PR DESCRIPTION
**Pull request by GheorgheP**
- 	Applied `fw_call()` on all option types before render and save
 - 	Added `fw_get_option_default_value()`
 - 	Replace `fw_get_options_values_from_input` with `fw_get_options_default_values` in `FW_Db_Options_Model::get`

### CODE REVIEW

**Comment by danyj** [comment]
can you explain `fw_call() `a bit

if I have this in options array 

	'something'    => array(
		'type'  => 'text',
		'label' => __( 'Title', 'fw' ),
		'desc'  => __( 'Icon title', 'fw' ),
		'value' => 'my default'
	)

is 

`fw_get_db_settings_option('something',null);
`

going to return `my default ` ?

**Comment by GheorgheP** [comment]
As you can see I closed the pull request for now, as I'm sill working on this,

But the logic is this: `value from db` else `your default` else `option type default value from defaults`

What i want to do is to stop the `get_value_from_input` to be called on frontend as it should be called only when the option value is insert in database, not when the value is selected from database.

`fw_call` doesn't have to do anything with this, as you see there are 3 commits. If you want more details about `fw_call` and why I added it in `render` and `get_value_from_input` I can provide some info.

**Comment by danyj** [comment]
I just want to make sure that default values are used as before , 

if null is set as default and there are no saved vals in db 

`fw_get_db_settings_option('something',null);`

 than the default value is pulled from options array

**Comment by andreiglingeanu** [comment]
@danyj Yes, you'll use it as before. `fw_call()` is [smart](https://github.com/ThemeFuse/Unyson/blob/fa1da6b8687869875c299e5bf56ffc06b4ea5395/framework/helpers/general.php#L1950-L1956) enough to distinguish primitive values from `FW_Callback` ones.

**Comment by GheorgheP** [comment]
Yes, now it doesn't return the `default`, but I alreadu modified the `fw_get_option_default_value`, so it checks for value in `$option`:

```
function fw_get_option_default_value( array $option ) {
	return isset( $option['value'] )
		? $option['value']
		: fw()
			->backend
			->option_type( fw_akg( 'type', $option ) )
			->get_defaults( 'value' );
}
```

**Comment by GheorgheP** [comment]
Thanks @danyj  for pointing this.

**Comment by GheorgheP** [comment]
Please refer my new pull request: https://github.com/ThemeFuse/Unyson/pull/2342

**Comment by danyj** [comment]
reason for this is that we need to make sure themes work on install without going into theme setting and hitting save . In order for that to work I used null as default value in all calls for fw_get_db_settings_option which  than reads the default value from options array.  @moldcraft  made this long time ago I think so lets just make sure that still works.

**Comment by GheorgheP** [comment]
Ok, could you test it out and see if it doesn't break the functionality of your settings?

**Comment by danyj** [comment]
@GheorgheP , on it, will report back

**Comment by danyj** [comment]
@GheorgheP , looks ok

**Comment by danyj** [comment]
Not sure if this change affected this but just so you know
https://github.com/ThemeFuse/Unyson/issues/2353

**Pull request closed without merging**
