### PR TITLE
Refactor icon-v2 option type

### PR DESCRIPTION
**Pull request by andreiglingeanu**
Long story short, this pull request moves `icon-v2` from [this](http://recordit.co/4iVYtsmCFD) to [that](http://recordit.co/q6nxjxWnTm). More details below.

<hr>

Aside from `icon-v2`, this pull request introduces more thing to consider.

1. [`lazy-tabs`](https://github.com/ThemeFuse/Unyson/pull/1942/files#diff-8b91e960afeccbf00f729b16973af81fR8) option for tabs, which disabled completely lazy tabs for this particular tab instance
2. `emptyHtmlOnClose` option for `fw.OptionsModal`

<hr>

_Back to `icon-v2`._ 

First thing to notice is that we no longer require a very long localize on the frontend which a causes a big bottleneck for browser rendering mechanism. https://github.com/ThemeFuse/Unyson/issues/1920#issuecomment-242046252. Instead, we load all the data only when we need by transporting it via [AJAX](https://github.com/ThemeFuse/Unyson/pull/1942/files#diff-fa52f364c3449494110a7a1cf3fb1713R372), which happens unnoticed for the user. PROFIT.

[One more important thing](https://github.com/ThemeFuse/Unyson/pull/1942/files#diff-487c9acfb85c5f4f5de26def274c3e78R49) to state is that we introduced `admin_wp_enqueue_handle` and `frontend_wp_enqueue_handle` which allows you to enqueue some _already registered_ CSS files on the frontend or admin. We don't want to double-load anything. Check [`fw-font-awesome`](https://github.com/ThemeFuse/Unyson/pull/1942/files#diff-487c9acfb85c5f4f5de26def274c3e78R3140) and [`fw-unycon`](https://github.com/ThemeFuse/Unyson/pull/1942/files#diff-487c9acfb85c5f4f5de26def274c3e78R380) for examples.

Next, `icon-v2` respects user-defined actions and hooks even more, it doesn't require too much CSS and fonts on the frontend and on the admin side.

For more details, check the code itself.

### CODE REVIEW

**Comment by andreiglingeanu** [comment]
I've committed all the changes directly to unyson. All of the text below is just for reference.

**Comment by moldcraft** [comment]
It is 100% compatible with previous `icon-v2`? In case some users already started using it

**Comment by andreiglingeanu** [comment]
@moldcraft Yep.

**Comment by danyj** [comment]
@andreiglingeanu   can I rely on the lazy_tabs option per tab?

**Comment by andreiglingeanu** [comment]
> can I rely on the lazy_tabs option per tab?

Yes, it works fine.

**Comment by danyj** [comment]
tested works as needed , thnx!

**Pull request closed without merging**
