### PR TITLE
Add ability to mock out $_* globals

### PR DESCRIPTION
**Pull request by mowshon**
Add ability to mock out PHP globals in FW_Request

### CODE REVIEW

**Comment by andreiglingeanu** [comment]
We need this feature in order to be able to _fake_ out data that unyson uses in some helpers.

**Comment by andreiglingeanu** [comment]
@moldcraft Would be nice to write some tests. It's very tedious to go about checking manually every feature we add.

**Comment by moldcraft** [comment]
> in some helpers.

Which helpers?

> it would be nice to write some tests

I added tests https://github.com/ThemeFuse/Unyson/tree/master/tests/unit

But one day (a couple of months ago) travis failed https://travis-ci.org/ThemeFuse/Unyson
It's not the problem in tests, but in the script that execute the tests. I copied the script from another place (I can't find the source now) and I didn't figured out how it actually works, it worked and I just started to write tests.
It will be great if somebody will fix the script and travis will work again.

**Comment by andreiglingeanu** [comment]
@moldcraft [This](https://github.com/ThemeFuse/Unyson/blob/3ce95f82d1a7aee1e9ecdca9020e0f2641a648f9/framework/core/components/backend.php#L1100) one. I have used it to get the html for form that have to be added in `Edit` modal for shortcode. Used it to get default values for a list of options.

Why: `item.view.modal.get('values') == {}` till user clicks `Save` in the shortcode modal.

Maybe there is a better way to get default values for options?

**Comment by andreiglingeanu** [comment]
[Maybe](https://cloud.githubusercontent.com/assets/2979628/11787335/bfbd9980-a293-11e5-86dd-21f9096f0076.png) you have wrong usage of the [install-wp-tests.sh](https://github.com/wp-cli/sample-plugin/blob/master/bin/install-wp-tests.sh#L5) script?

**Comment by moldcraft** [comment]
I don't know, it worked and at one time it stopped, I did no changes in script or tests.

**Comment by moldcraft** [comment]
I will reply at https://github.com/ThemeFuse/Unyson/pull/1116#issuecomment-164491155 later

**Comment by andreiglingeanu** [comment]
@moldcraft Maybe @wp-cli update introduced the error, who knows.

@moldcraft Okay. Ideally I would want this, without a change to the unyson:

```php
$options =  [
    "unique_id" => [
        "type" => "unique",
    ],
    ...
],

some_magic_function_that_will_give_me_defaults( $options );
```

**Comment by moldcraft** [comment]
```php
add_action('fw_init', function(){
	$options = array(
		'unique_id' => array(
			'type' => 'unique',
		),
		'text_1' => array(
			'type' => 'text',
			'value' => 'Default Value 1',
		),
		'text_2' => array(
			'type' => 'text',
			'value' => 'Default Value 2',
		),
		'text_3' => array(
			'type' => 'text',
		),
	);

	$values = fw_get_options_values_from_input($options, array('text_2' => 'POST Value'));

	fw_print($values);
});
```

**Comment by andreiglingeanu** [comment]
@moldcraft would check it. Looks like that's what I need. Thanks. We can close pull request for now.

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/pull/1116#issuecomment-164482313

fixed https://github.com/ThemeFuse/Unyson/commit/069fc9cc0a8139c81af0dae275234af620d78c9e

**Comment by andreiglingeanu** [comment]
:+1:

**Pull request closed without merging**
