### PR TITLE
Fix fw_current_url() server name bug

### LINKED ISSUE #2442: Extension settings save form issue
As stated previously in #1689 there is a problem with form "action" attribute and it's value.
Currently that value is populated via `$_SERVER['SERVER_NAME']` however as stated in #1262 
That variable doesn't always holds valid url.
The issue with my setup ( I'm using nginx ) is that my server name is a **regex** witch is perfectly valid in nginx.
Nginx accepts wildcards and regular expressions:
http://nginx.org/en/docs/http/server_names.html

So in my case:
`$_SERVER['SERVER_NAME']='~^theme-1\\..+\\.xip\\.io$'`
and
`$_SERVER['HTTP_HOST']='theme-1.192.168.3.101.xip.io'`

So `form action` has invalid url.

### PR DESCRIPTION
**Pull request by ivandotv**
fixes #2442
Using regex to determine if `SERVER_NAME` is valid url.

regex test:
https://regex101.com/r/ty0Pzg/1

### CODE REVIEW

**Comment by andreiglingeanu** [comment]
@ivandotv Looks fine to me. I wonder why we're not `$_SERVER['HTTP_HOST']` in every case.

I didn't know that nginx is passing the raw `server_name` directive contents (as it is defined in the conf) to the `php-fpm`. `HTTP_HOST` seems more stable in this case.

**Comment by GheorgheP** [comment]
Yes, I'm aware to about the `fw_current_url()` function, as it uses the `$_SERVER` global to build the URL as this is an unsafe solution, I will investigate this deeper and come out with a solution.

**Comment by andreiglingeanu** [comment]
@ivandotv Travis build is failing, it gives a syntax error. Please fix it before merging.

**Comment by andreiglingeanu** [comment]
@ivandotv I've attached a pull request to your fork. Please merge it then I'll merge you here.

<hr>

_Please check this checkbox from now on, so that we can collaborate in a bit more easier fashion._
comparing_ivandotv_master___andreiglingeanu_master_ _ivandotv_unyson

**Comment by andreiglingeanu** [comment]
Everything fine. Good to merge.

The only problem is that tests fail in Unyson for php7.0, but that's another problem which is not related to the current issue.

**Comment by ivandotv** [comment]
@andreiglingeanu 
I was away from computer during the weekend, thanks for fixing the code ( I wrote it in browser, really fast )

**Comment by andreiglingeanu** [comment]
No problem, you're welcome.

**Comment by andreiglingeanu** [comment]
The tests are passing under my local setup, it must be some problems with travis env.

**Pull request merged**
