### PR TITLE
turn on selectize remove_button plugin

### PR DESCRIPTION
**Pull request by danyj**

### CODE REVIEW

**Comment by GheorgheP** [comment]
What is this doing?

**Comment by danyj** [comment]
@GheorgheP  https://github.com/ThemeFuse/Unyson/issues/2649

**Comment by danyj** [comment]
@andreiglingeanu  can this be merged please

**Comment by andreiglingeanu** [comment]
Is this affecting selectize inputs with only one possible value? Will the button show up in this case?

**Comment by danyj** [comment]
let me test

**Comment by andreiglingeanu** [comment]
@danyj Please. I'll merge it afterwards.

**Comment by danyj** [comment]
nope ,  http://prntscr.com/g6adt1


if limit is set only one selection is possible and there are not buttons

**Comment by andreiglingeanu** [comment]
Awesome!

**Comment by danyj** [comment]
@andreiglingeanu  darn thing  look at this beauty 

http://jsfiddle.net/Shinov/csNgy/

http://take.ms/p5u1i

can you change it to 

   plugins: ['remove_button','drag_drop'],

**Comment by andreiglingeanu** [comment]
Can you quickly create one more pull request? There's no way to commit directly to `master`, I can only merge pull requests.

**Comment by danyj** [comment]
on it

**Comment by danyj** [comment]
done https://github.com/ThemeFuse/Unyson/pull/2746

**Pull request merged**
