### PR TITLE
Added clone button for addable popups fixes #1419

### LINKED ISSUE #1419: Clone button for addable-popup
https://github.com/ThemeFuse/Unyson/issues/1418#issuecomment-205756179

### PR DESCRIPTION
**Pull request by danyj**
Added clone button. It respects  popups limits and hides clone buttons if limits are reached.

### CODE REVIEW

**Comment by andreiglingeanu** [comment]
@danyj Looks good and works fine too.

Do you think we may need a clone button for [addable boxes](https://d2ppvlu71ri8gs.cloudfront.net/items/2M0H3H1D2S1d0V2w2704/Screen%20Shot%202017-05-01%20at%209.43.35%20AM.png?v=604dc782) too?

**Comment by danyj** [comment]
@andreiglingeanu 

> do you think we may need a clone button for addable boxes too?

yes , that was original issue #1418 

did you make it already or ?

**Comment by andreiglingeanu** [comment]
@danyj Please make the required changes and we'll get that merged into Unyson.

**Comment by danyj** [comment]
If you are talking about addable box

@andreiglingeanu   I submited this here , https://github.com/ThemeFuse/Unyson/issues/1418

it is crude and I think I need your help on it

**Comment by danyj** [comment]
@andreiglingeanu   there is space between every method here 

https://github.com/danyj/Unyson/blob/70f903c6192f2257cb40a4f2d80c4d0780101ed1/framework/includes/option-types/addable-popup/static/js/scripts.js#L138-L177

dont see why I should  remove the one you mentioned

**Comment by andreiglingeanu** [comment]
It should be an empty line and not contain spaces :)

**Comment by danyj** [comment]
never mind , I missed one , fixed

**Comment by andreiglingeanu** [comment]
Thank you.

**Comment by andreiglingeanu** [comment]
Please do start a new pull request for boxes and we'll work out an implementation for it together.

**Comment by thednp** [comment]
Question: will this work with `addable-popup` and `addable-popup-full` as well?

**Comment by danyj** [comment]
@thednp  it works for addable-popup but what is addable-popup-full ?

**Comment by thednp** [comment]
Same, but in full width.

**Comment by danyj** [comment]
never used it , i see is using same script as addable popup so yes it would work for both

**Pull request merged**
