### PR TITLE
trigger an event on TS ajax save

### PR DESCRIPTION
**Pull request by andreiglingeanu**

### CODE REVIEW

**Comment by moldcraft** [comment]
`fw-form-helpers.js` is a general purpose script, not only for TS. It is used in frontend, where fwEvents is not defined. http://manual.unyson.io/en/latest/helpers/php.html#ajax-submit

**Comment by moldcraft** [comment]
Trigger the event somewhere [here](https://github.com/ThemeFuse/Unyson/blob/v2.5.1/framework/views/backend-settings-form.php#L249)

**Comment by andreiglingeanu** [comment]
@moldcraft what about triggering a general purpose success event on the form element?

**Comment by andreiglingeanu** [comment]
I'm okay with receiving an event as you told me on your last comment. I haven't seen it before posting. I was on my phone.

**Comment by moldcraft** [comment]
[There](https://github.com/ThemeFuse/Unyson/blob/v2.5.1/framework/views/backend-settings-form.php#L357) is already an event

**Comment by andreiglingeanu** [comment]
@moldcraft Thank you.

**Pull request closed without merging**
