### PR TITLE
Issue#2563

### PR DESCRIPTION
**Pull request by GheorgheP**

### CODE REVIEW

**Comment by danyj** [comment]
@GheorgheP did you see this 
https://github.com/ThemeFuse/Unyson/issues/2494#issuecomment-298009594

the reset does not work with that change

**Comment by GheorgheP** [comment]
Yes. Actually I wanted to pull only this commit: https://github.com/ThemeFuse/Unyson/pull/2565/commits/3bbb0af4c8ca536366b59725eb1b624e9a98e9ce

**Comment by andreiglingeanu** [comment]
@GheorgheP Did you gave up saving only a subset of options eventually?

**Comment by GheorgheP** [comment]
No, I wanted to pull only this commit https://github.com/ThemeFuse/Unyson/pull/2565/commits/3bbb0af4c8ca536366b59725eb1b624e9a98e9ce

The solution with partial saving is not ready for production.

**Pull request closed without merging**
