### PR TITLE
Feature dynamic multi picker

### PR DESCRIPTION
**Pull request by andreiglingeanu**
Introduce `multi-picker` with detached picker.

[Documentation](http://manual.unyson.io/en/latest/options/built-in/multi-picker.html#dynamic-multi-picker) | [Live screencast](https://cl.ly/lRj7)

<hr>

<details><summary>Test</summary><p>

```php
$options = array(
	'gadget' => array(
		'type'    => 'select',
		'choices' => array(
			'phone'  => __('Phone', '{domain}'),
			'laptop' => __('Laptop', '{domain}')
		),
	),

	'multi-picker' => array(
		'type' => 'multi-picker',

		'picker' => 'gadget',

		'choices' => array(
			'phone' => array(
				'text' => array(
					'type' => 'text'
				)
			),

			'laptop' => array(
				'text' => array(
					'type' => 'icon-v2'
				)
			)
		)
	),

	'second-multi-picker' => array(
		'type' => 'multi-picker',

		'picker' => 'gadget',

		'choices' => array(
			'phone' => array(
				'text' => array(
					'type' => 'typography'
				)
			),

			'laptop' => array(
				'text' => array(
					'type' => 'icon'
				)
			)
		)
	),

);

```

</p></details>

### CODE REVIEW

**Comment by andreiglingeanu** [comment]
cc. @GheorgheP @danyj @andronic90 Can you guys try that and give me some feedback?

**Comment by danyj** [comment]
did you test this in separate tabs ? lazy_tabs ?

**Comment by andreiglingeanu** [comment]
It will update properly if picker is in a separated tab. With lazy tabs it is a bit questionable but it should work fine overall.

**Comment by danyj** [comment]
looks great!  tested in all 3 ( gadget, picker1,picker2) separated in to 3 different tabs ,  and switched properly. did not test frontend but it should not be an issue.

**Comment by andreiglingeanu** [comment]
Awesome! I think we are ready for that to be merged.

**Pull request merged**
