### PR TITLE
add wrapWithTable option to fw.soleModal

### PR DESCRIPTION
**Pull request by andreiglingeanu**
attempt to solve #1076

### CODE REVIEW

**Comment by andreiglingeanu** [comment]
@moldcraft please review my realisation.

**Comment by andreiglingeanu** [comment]
Sorry. Added one more improvement into this pull request. Meant to create another one.

**Comment by andreiglingeanu** [comment]
@moldcraft This pull request is a mess. Can you please apply just b67b319cbee8415ac3de1747d249cdc7aba506cd and 34221a5fd3f0400b095aaa53d121b6ce6d73ec4d and close it?

**Comment by moldcraft** [comment]
P.S. Useful bash command to apply patches

```
curl https://github.com/ThemeFuse/Unyson/commit/b67b319cbee8415ac3de1747d249cdc7aba506cd.diff | git apply
```

**Pull request closed without merging**
