### PR TITLE
Install/update extension/theme via custom url

### PR DESCRIPTION
**Pull request by ViorelEremia**
http://manual.unyson.io/en/latest/extensions/cookbook.html

### CODE REVIEW

**Comment by danyj** [comment]
@ViorelEremia  how does `purchase_key  `work ?

**Comment by ViorelEremia** [comment]
@danyj you can add in your theme settings some inputs where user need to insert your purchase key from envato or your custom purchase key and in manifest.php you extract it. exemple for envato, you add two inputs username and purchase key you save them into a custom field in db and in manifest extract them you will automatically have access to them on your server when the extension wants to install or update.

**Comment by danyj** [comment]
> you will automatically have access to them on your server

**Comment by ViorelEremia** [comment]
Yes, on your server you get from body of $_POST request see index.php from docs 
```$set = json_decode( file_get_contents( 'php://input' ), true );```

**Pull request merged**
