### PR TITLE
chore($fw.Modal): remove focus hack which used to prevent jumping

### LINKED ISSUE #2399: remove fw.Modal jump hack from unyson once core releases it
https://core.trac.wordpress.org/ticket/39859

https://github.com/ThemeFuse/Unyson/pull/2388#issuecomment-279388311

### PR DESCRIPTION
**Pull request by andreiglingeanu**
Finally fix #2399. https://core.trac.wordpress.org/ticket/39859 got merged in `4.9.3` in core, everything works now without any hacks from our side!

More context for the issue: #2388

### CODE REVIEW

**Comment by andreiglingeanu** [comment]
Please test

cc. @ViorelEremia @danyj

**Comment by danyj** [comment]
I would wait till 4.9.5, all theme devs on TF need to support 2 versions back so removing this now can result in new tickets from users who are on 4.9.1,4.9.2

**Comment by andreiglingeanu** [comment]
No one's going to notice it, it's a very simple jump & a lot of users didn't even noticed it and I bet `4.9.5` is not so far to come...

**Comment by ciorici** [comment]
@andreiglingeanu seems that your bet was wrong :)

**Comment by andreiglingeanu** [comment]
Hmm, that definitely should not happen... We can temporarily restore the previously made hack anyway

**Comment by danyj** [comment]
lol  @andreiglingeanu  I had to do this 
have a nice weekend! :)  dont get mad 


cea092750c958478ecac42c78a155fa6

**Comment by andreiglingeanu** [comment]
😁thanks! Same to you!

**Comment by danyj** [comment]
@andreiglingeanu  looks like we will need this again , with latest Unyson 2.7.20 jumping is back big time

**Pull request merged**
