### PR TITLE
post ids to integer multi-select option type & post_type define #2862

### PR DESCRIPTION
**Pull request by hlaporthein**
changed post_ids to integer as @ViorelEremia did and then 'post_type' define from post ids. That would be great if we could directly use from 'source' => 'custom_post_type_name'. But, I don't know which function to get 'source' value.

### CODE REVIEW

**Comment by ViorelEremia** [comment]
Okay, I understand what you did, I'll test it tomorrow, today would be good to have a rest :)

**Comment by ViorelEremia** [comment]
@hlaporthein No need to extract post type they may be more, for example, you can send in source 'population' => 'posts', 'source' => array( 'page', 'post' ), then all post_types are imploded: https://github.com/ThemeFuse/Unyson/blob/master/framework/includes/option-types/multi-select/class-fw-option-type-multi-select.php#L98
In this case, by your code all posts will not be extracted but only posts with post type from first post.
Then the option is rebuild we need post_type = any because user can choose posts with different post types.

**Comment by hlaporthein** [comment]
Hello @ViorelEremia , post_type **any** doesn't work in WP_Query. For example if we test like that below, it won't work, Please test it in functions.php.

```
function post_type_tester() {

	$query = new WP_Query( array(
		'post_type'      => 'any',
		'post__in'       => array(448,449, 450, 451, 452, 453, 454),
		'posts_per_page' => 10,
		'fields'         => 'ids'
	) );
d($query->get_posts());


}
add_action('init', 'post_type_tester', 999);
```

**Comment by ViorelEremia** [comment]
Code in functions.php 
`function post_type_tester() {

	$query = new WP_Query( array(
		'post_type'      => 'any',
		'post__in'       => array( 7, 1, 16 ),
		'posts_per_page' => 10,
		'fields'         => 'ids'
	) );


	echo '<pre class="v-debug">';
	print_r( $query );
	echo '</pre>';
}
add_action( 'init', 'post_type_tester', 999 );`
result from query:
`[posts] => Array
        (
            [0] => 16
            [1] => 7
            [2] => 1
        )
`
Post types of post: post, page.
For me it works.

**Comment by hlaporthein** [comment]
Hi @ViorelEremia  thank for quick response.does it work for custom post type not post and page? I have tested it, it doesn't work for custom post type.

**Comment by ViorelEremia** [comment]
Yes it works also width custom post types: 
`add_action( 'init', 'codex_book_init' );
/**
 * Register a book post type.
 *
 * @link http://codex.wordpress.org/Function_Reference/register_post_type
 */
function codex_book_init() {
	$labels = array(
		'name'               => _x( 'Books', 'post type general name', 'your-plugin-textdomain' ),
		'singular_name'      => _x( 'Book', 'post type singular name', 'your-plugin-textdomain' ),
		'menu_name'          => _x( 'Books', 'admin menu', 'your-plugin-textdomain' ),
		'name_admin_bar'     => _x( 'Book', 'add new on admin bar', 'your-plugin-textdomain' ),
		'add_new'            => _x( 'Add New', 'book', 'your-plugin-textdomain' ),
		'add_new_item'       => __( 'Add New Book', 'your-plugin-textdomain' ),
		'new_item'           => __( 'New Book', 'your-plugin-textdomain' ),
		'edit_item'          => __( 'Edit Book', 'your-plugin-textdomain' ),
		'view_item'          => __( 'View Book', 'your-plugin-textdomain' ),
		'all_items'          => __( 'All Books', 'your-plugin-textdomain' ),
		'search_items'       => __( 'Search Books', 'your-plugin-textdomain' ),
		'parent_item_colon'  => __( 'Parent Books:', 'your-plugin-textdomain' ),
		'not_found'          => __( 'No books found.', 'your-plugin-textdomain' ),
		'not_found_in_trash' => __( 'No books found in Trash.', 'your-plugin-textdomain' )
	);

	$args = array(
		'labels'             => $labels,
		'description'        => __( 'Description.', 'your-plugin-textdomain' ),
		'public'             => true,
		'publicly_queryable' => true,
		'show_ui'            => true,
		'show_in_menu'       => true,
		'query_var'          => true,
		'rewrite'            => array( 'slug' => 'book' ),
		'capability_type'    => 'post',
		'has_archive'        => true,
		'hierarchical'       => false,
		'menu_position'      => null,
		'supports'           => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments' )
	);

	register_post_type( 'book', $args );
}

function post_type_tester() {

	$query = new WP_Query( array(
		'post_type'      => 'any',
		'post__in'       => array( 7, 1, 16, 19 ),
		'posts_per_page' => 10,
		'fields'         => 'ids'
	) );


	echo '<pre class="v-debug">';
	print_r( $query );
	echo '</pre>';
}

add_action( 'init', 'post_type_tester', 999 );`

**Comment by hlaporthein** [comment]
Hi @ViorelEremia , I found the error. Thanks for your helps. The problem is when I register ** custom post type **, I set * 'exclude_from_search' => true, *. That's why **post_type => any**  can't search the posts.

**Pull request closed without merging**
