### PR TITLE
add the abillity to enqueue all static at once for an extension

### PR DESCRIPTION
**Pull request by andreiglingeanu**

### CODE REVIEW

**Comment by moldcraft** [comment]
I don't agree with this.

* `{extension}/static/js/`
* `{extension}/static/css/`

can contain assets for only a specific page (that throw errors on other pages), or assets can be grouped in directories (like some jquery libraries)

* `{extension}/static/js/jquery.whatever/js/jquery.whatever.js`
* `{extension}/static/jquery.whatever/js/jquery.whatever.js`

So better create an abstract class that will extend `FW_Extension`, put it in your theme or theme plugin and use for your own extensions.

**Comment by moldcraft** [comment]
Also handles name is strict, there can be dependencies between scripts/styles, so auto-naming them is not good.

**Comment by andreiglingeanu** [comment]
@moldcraft I see what you're saying. I love the idea of executing adding every script I need and just make the checks in js. Also I can wrap this call into a check that will do actions just on a particular page:

```php
if (im_on_the_page_i_need()) {
  fw()->extensions->get('ext')->enqueue_all_static();
}
```

> Also handles name is strict, there can be dependencies between scripts/styles, so auto-naming them is not good.
I'll better agree to some strict, but correct, naming rather messing myself everytime I'll need to add a new script.

But those are just my own preferences, I'll stick with a subclass of `FW_Extension` in my own code. Thank you.

**Comment by danyj** [comment]
@andreiglingeanu   how do you enque any extension static ? 
I need this for portfolio extension if it is on frontpage

**Comment by andreiglingeanu** [comment]
@danyj That's what I'm using. https://gist.github.com/andreiglingeanu/bc1afacf155753edb771967edc78b9b3

Then extend your extension from `PREFIX_Unyson_Extension`.

The trick here is to load this class at the right moment. It turns out the best moment to do this is by hooking to [this action](https://github.com/ThemeFuse/Unyson/pull/1363/commits/a7c146c428449a42c04c9bd158024f6cf888f289).

You'll have to call `enqueue_all_static` method from your `static.php` file, like this:
```php
fw_ext('your_extension')-> enqueue_all_static();
```

There's a lot of flexibility in this, you'll get it only by reading the code. It's really simple.

**Pull request closed without merging**
