### PR TITLE
feat($manager): introduce a filter that allow disabling unyson button

### PR DESCRIPTION
**Pull request by andreiglingeanu**
```php
add_filter(
    // or __return_true, maybe also include a custom callback for even more complex logic
	'fw_backend_enable_custom_extensions_menu', '__return_false'
);
```

### CODE REVIEW

**Comment by danyj** [comment]
what menu would that be?, the hook states `custom_extensions_menu `, implying ability to disable custom user extensions

**Comment by andreiglingeanu** [comment]
It has nothing to do with the ability to disable custom user extensions. The filter just allows someone to remove the Unyson button from Core sidebar, if they wish to. Nothing's changed by default.

**Comment by danyj** [comment]
I think this would be more appropriate than 


`'fw_backend_disable_unyson_from_menu', '__return_true'`

**Comment by danyj** [comment]
or 

`'fw_backend_enable_unyson_in_menu', '__return_false'`

**Comment by andreiglingeanu** [comment]
I choose the name based on the already existing action:

https://github.com/ThemeFuse/Unyson/blob/3335a5c736e6627f6cbc7e3898fba5c412fc9b8d/framework/core/components/extensions/manager/class--fw-extensions-manager.php#L753-L757

**Pull request merged**
